parallel-jobs = 1
strict-sigcheck = false

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
patcher-args = "-e 'Change header' -Ocustom=icons/YouTube/header -e 'Custom branding' -OcustomIcon=icons/YouTube/branding -OcustomName=YouTube Morphe"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[YouTube.patches]
"github:MorpheApp/morphe-patches" = []

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
patcher-args = "-e 'Change header' -Ocustom=icons/Music/header -e 'Custom branding' -OcustomIcon=icons/Music/branding -OcustomName='Youtube Music Morphe'"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Music.patches]
"github:MorpheApp/morphe-patches" = []

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
patcher-args = "-e 'Custom branding name for Reddit' -OappName='Reddit'"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Reddit.patches]
"github:MorpheApp/morphe-patches" = []

[Twitter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
brand = "Piko"
arch = "arm64-v8a"
version = "auto"

[Twitter.patches]
"github:crimera/piko" = ["Bring back twitter", "Browse tweet object", "Dynamic color"]
"gitlab:inotia00/x-shim" = []

[Instagram]
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
brand = "Piko"
arch = "arm64-v8a"
version = "auto"

[Instagram.patches]
"github:crimera/piko" = []

[WARP]
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[WARP.patches]
"github:rushiranpise/morphe-patches" = []

[Cashew]
apkmirror-dlurl = "https://www.apkmirror.com/apk/dapper-app-developer/cashew-expense-budget-tracker"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Cashew.patches]
"github:rushiranpise/morphe-patches" = []

[Splitwise]
apkmirror-dlurl = "https://www.apkmirror.com/apk/splitwise/splitwise/"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Splitwise.patches]
"github:rushiranpise/morphe-patches" = []

[Truecaller]
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Truecaller.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Xodo]
apkmirror-dlurl = "https://www.apkmirror.com/apk/apryse-software-inc/xodo-pdf-reader-editor"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Xodo.patches]
"github:hoo-dles/morphe-patches" = []

[Amazon-India]
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-india-shop-pay"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Amazon-India.patches]
"github:rushiranpise/morphe-patches" = []

[Amazon-Prime-Video]
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Amazon-Prime-Video.patches]
"github:hoo-dles/morphe-patches" = []

[TickTick]
apkmirror-dlurl = "https://www.apkmirror.com/apk/ticktick-limited/ticktick-to-do-list-with-reminder-day-planner/"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[TickTick.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []
