parallel-jobs = 1
strict-sigcheck = false

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/youtube/com.google.android.youtube"
patcher-args = "-e 'Change header' -Ocustom=icons/YouTube/header -e 'Custom branding' -OcustomIcon=icons/YouTube/branding -OcustomName='YouTube Morphe'"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[YouTube.patches]
"github:MorpheApp/morphe-patches" = []

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/youtube-music/com.google.android.apps.youtube.music"
patcher-args = "-e 'Change header' -Ocustom=icons/Music/header -e 'Custom branding' -OcustomIcon=icons/Music/branding -OcustomName='Youtube Music Morphe'"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Music.patches]
"github:MorpheApp/morphe-patches" = []

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/reddit/com.reddit.frontpage"
patcher-args = "-e 'Custom branding name for Reddit' -OappName='Reddit'"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Reddit.patches]
"github:MorpheApp/morphe-patches" = []

[Twitter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/x/com.twitter.android"
brand = "Piko"
arch = "arm64-v8a"
version = "auto"

[Twitter.patches]
"github:crimera/piko" = ["Bring back twitter", "Browse tweet object", "Dynamic color"]
"gitlab:inotia00/x-shim" = []

[Instagram]
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/instagram/com.instagram.android"
github-dlurl =  "https://github.com/nullcpy/apks/releases/tag/com.instagram.android"

brand = "Piko"
arch = "arm64-v8a"
version = "auto"

[Instagram.patches]
"github:crimera/piko" = []

[WARP]
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet"
uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/1-1-1-1-warp/com.cloudflare.onedotonedotonedotone"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[WARP.patches]
"github:rushiranpise/morphe-patches" = []

[Cashew]
apkmirror-dlurl = "https://www.apkmirror.com/apk/dapper-app-developer/cashew-expense-budget-tracker"
uptodown-dlurl = "https://cashew.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/cashew/com.budget.tracker.finance"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Cashew.patches]
"github:rushiranpise/morphe-patches" = []

[Splitwise]
apkmirror-dlurl = "https://www.apkmirror.com/apk/splitwise/splitwise/"
uptodown-dlurl = "https://splitwise.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/splitwise/com.Splitwise.SplitwiseMobile"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Splitwise.patches]
"github:rushiranpise/morphe-patches" = []

[Truecaller]
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
uptodown-dlurl = "https://truecaller.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/truecaller/com.truecaller"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Truecaller.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Xodo]
apkmirror-dlurl = "https://www.apkmirror.com/apk/apryse-software-inc/xodo-pdf-reader-editor"
uptodown-dlurl = "https://xodo-docs.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/xodo-pdf-reader/com.xodo.pdf.reader"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Xodo.patches]
"github:hoo-dles/morphe-patches" = []

[Amazon-India]
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-india-shop-pay"
uptodown-dlurl = "https://amazon-india.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/amazon-india-shop-pay/in.amazon.mShop.android.shopping"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Amazon-India.patches]
"github:rushiranpise/morphe-patches" = []

[Amazon-Prime-Video]
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/amazon-prime-video/com.amazon.avod.thirdpartyclient"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[Amazon-Prime-Video.patches]
"github:hoo-dles/morphe-patches" = []

[TickTick]
apkmirror-dlurl = "https://www.apkmirror.com/apk/ticktick-limited/ticktick-to-do-list-with-reminder-day-planner/"
uptodown-dlurl = "https://ticktick.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/ticktick/com.ticktick.task"
brand = "morphe"
arch = "arm64-v8a"
version = "auto"

[TickTick.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []
